### ISSUE TITLE
Cache-Control Header max-age=0 is Implicit in no-store

### ISSUE THREAD

**Issue by crypticrabbit** [PayString/rfcs#23]
The rfcs require the 'Cache-Control' response header be set to 'max-age=0', however, it appears to be more appropriate to use the 'no-store' directive, as it is [more broad](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) in that it assumes 'max-age=0' as well as 'must-revalidate'.

Credit to @raredata for talking through which headers are appropriate with me. Markus also observed that the 'no-transform' directive might be appropriate.

Also credit to @XRPL-Labs, whose PayID implementation first alerted me to the 'no-store' directive.

**Comment by aanchal4** [comment]
Thanks @crypticrabbit for bringing this up. Sounds reasonable to me! Will update the RFC in next iteration.

**Comment by jscottbranson** [comment]
Just circling back to this, thanks for merging.
